# Generated by Django 5.1.4 on 2025-02-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
