# Generated by Django 5.1.4 on 2025-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_genre_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(related_name='videos', to='videoflix_app.genre'),
        ),
    ]
