# Generated by Django 5.1.4 on 2025-01-02 12:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_video_genres'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_title_ci'),
        ),
    ]
