# Generated by Django 5.1.4 on 2025-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_remove_genre_unique_title_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
