name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  Repository
        uses: actions/checkout@v4

      - name: SSH and Pull Latest Code
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          key: "${{ secrets.SERVER_SSH_KEY }}"
          script: |
            cd /home/oezkan/projects/videoflix_backend
            
            git reset --hard
            git pull origin main
            
            # Stelle sicher, dass das Skript ausführbar ist
            chmod +x ./scripts/generate_env.sh
            
            # Führe das Skript aus, um die .env-Datei zu generieren
            ./scripts/generate_env.sh