name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django

      - name: Set up Environment Variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=videoflix_project.settings" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Tests
        run: |
          pytest users/tests/
          pytest videoflix_app/tests/
